// Xerus Master Orchestrator Types
// Type definitions for the master orchestrator agent
// Source: docs/planning/execution/xerus-master-prompt.md
//
// Split into:
//   xerus-master.constants.ts — slug names, tool names, HITL, delegation budget
//   xerus-master.tool-types.ts — all input/result interfaces, PlatformTool type

// Re-export everything from constants
export {
    XERUS_MASTER_SLUG,
    XERUS_MASTER_NAME,
    XERUS_CTO_SLUG,
    MAX_DELEGATION_DEPTH,
    MAX_DELEGATIONS_PER_REQUEST,
    MAX_PARALLEL_DELEGATIONS,
    DEFAULT_DELEGATED_TOKEN_BUDGET,
    HEARTBEAT_INTERVALS,
    PLATFORM_TOOLS,
    PLATFORM_TOOL_LIST,
    PLATFORM_TOOL_HITL,
    DEFAULT_DELEGATION_BUDGET,
} from './xerus-master.constants';

export type { HITLRequirement, DelegationBudget } from './xerus-master.constants';

// Re-export everything from tool-types
export type {
    PlatformTool,
    WorkspaceContext,
    XerusMasterConfig,
    DelegationContext,
    TeamDelegationContext,
    CallChainEntryType,
    CallChainEntry,
    CallChainCheckResult,
    CreateAgentInput,
    CloneAgentInput,
    SearchAgentsInput,
    UploadKbInput,
    AssignKbInput,
    SearchKbInput,
    CreateChannelInput,
    AddToChannelInput,
    CreateTaskInput,
    CreateSkillInput,
    SearchSkillsInput,
    SearchToolsInput,
    ConnectToolInput,
    UpdateAgentInput,
    ConfigureHeartbeatInput,
    GetStatusInput,
    PauseExecutionInput,
    ResumeExecutionInput,
    GetSessionStateInput,
    CompleteSessionInput,
    CompleteSessionResult,
    MemoryScope,
    QueryMemoryInput,
    WriteMemoryInput,
    AnalyzeMemoryPatternsInput,
    RegisterTriggerInput,
    ListTriggersInput,
    DeregisterTriggerInput,
    SearchOutputsInput,
    PlatformToolResult,
    AgentSearchResult,
    KbDocumentResult,
    ChannelResult,
    TaskResult,
    SkillResult,
    ToolResult,
    StatusResult,
    UpdateAgentResult,
    ConfigureHeartbeatResult,
    PauseExecutionResult,
    ResumeExecutionResult,
    SessionStateResult,
    MemorySearchResult,
    QueryMemoryResult,
    WriteMemoryResult,
    MemoryPattern,
    AnalyzeMemoryPatternsResult,
    TriggerResult,
    RegisterTriggerResult,
    ListTriggersResult,
    DeregisterTriggerResult,
    OutputEntry,
    SearchOutputsResult,
    HeartbeatInterval,
    HeartbeatCheckResult,
    HeartbeatFinding,
    HeartbeatResponse,
    ProactiveTaskSuggestion,
} from './xerus-master.tool-types';
